### ISSUE TITLE
when used as moduleNameMapper it breakes test using cx function from @emotion/css 

### ISSUE THREAD

**Issue by hbinkle** [eddyerburgh/jest-transform-stub#29]
See: https://github.com/emotion-js/emotion/issues/2699

**Comment by eddyerburgh** [comment]
Thanks for creating this issue.

The problem here is that the regex for module name mapper isn't strict enough—instead of matching module names with a .css extension, it's matching @emotion/css. You can fix this by updating the jest.config.js to use the recommended regex from the README:

```
module.exports = {
  //..
  moduleNameMapper: {
    "^.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$": "jest-transform-stub"
  },
}
```

Was this config generated for you? It's worth fixing the issue upstream if so

**Comment by hbinkle** [comment]
@eddyerburgh , thank you for your answer. This solves the problem.
